version: '3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: always
    networks:
      - prop-ie-network

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/prop-ie
      - JWT_SECRET=your-production-jwt-secret
      - PORT=5000
    depends_on:
      - mongodb
    restart: always
    networks:
      - prop-ie-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - prop-ie-network

networks:
  prop-ie-network:
    driver: bridge

volumes:
  mongodb_data:
